version: "3.8"

services:
  app:
    container_name: base-bot
    build:
      context: .
      dockerfile: Dockerfile
    command: "python -m app"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/base_bot
    env_file:
      - ".env"

    depends_on:
      - db
      - redis

  db:
    container_name: base-bot-postgres
    image: postgres:15.3-alpine3.18
    hostname: base_bot
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ".env"

  redis:
    container_name: base-bot-redis
    image: redis:7.2.2-alpine3.18
    hostname: base_bot
    restart: always
